name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.target.os }}
    strategy:
      matrix:
        target:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - os: macos-latest
            triple: x86_64-apple-darwin
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
        features: [ 'build-assimp', 'static-link' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      # LLVM comes preinstalled on Windows and macOS runners.
      - name: Install LLVM
        if: runner.os == 'Linux'
        uses: KyleMayes/install-llvm-action@v1
        with:
          directory: ${{ runner.temp }}/llvm
          cached: true
          version: '14.0'

      # CMake and Rust are preinstalled on all runners.

      - name: Update Rust
        run: |
          rustup default stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --target ${{ matrix.target.triple }} --features ${{ matrix.features }}

      - name: Package Assimp
        run: cargo run --bin package --target ${{ matrix.target.triple }} --bin package --features ${{ matrix.features }}
        env:
          RUSSIMP_PACKAGE_DIR: ./russimp-package

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: russimp-packages
          path: ${{ env.RUSSIMP_PACKAGE_DIR }}/*
        env:
          RUSSIMP_PACKAGE_DIR: ./russimp-package
